 module.exports = {
     apiEmpresa: require('./controllers/apiEmpresa'),
     apiCommon: require('./controllers/apiCommon'),
     apiNewUnits: require('./controllers/apiNewUnits'),
     apiunidadesvin: require('./controllers/apiunidadesvin'),
     apiinventario: require('./controllers/apiInventario'),
     apiConciliacion: require('./controllers/apiConciliacion'),
     apiAuditoria: require('./controllers/apiAuditoria'),
     apiDashboard: require('./controllers/apiDashboard'),
     apiEsquema: require('./controllers/apiEsquema'),
     apiFinanciera: require('./controllers/apiFinanciera'),
     apiInteres: require('./controllers/apiInteres'),
     apiTraspaso: require('./controllers/apiTraspaso'),
     apiAplicaPagos: require('./controllers/apiAplicaPagos'),
     apiproveedor: require('./controllers/apiProveedor'),
     apiReduccion: require('./controllers/apiReduccion'),
     apiTiie: require('./controllers/apiTiie'),
     apicrealote: require('./controllers/apicrealote'),
     apiFechaPromesa: require('./controllers/apiFechaPromesa'),
     apiReporte: require('./controllers/apiReporte'),
     apiSacarUnidad: require('./controllers/apiSacarUnidad'),
     apiNotificaciones: require('./controllers/apiNotificaciones')
 }
